### ISSUE TITLE
OpenTracing module reports 2 traces for a single request

### ISSUE THREAD

**Issue by arjun-1** [zio/zio-telemetry#130] opened 2020-04-22 09:08 UTC
Currently the opentracing module will report 2 traces for a single (1) request:
![Screenshot from 2020-04-22 10-56-47](https://user-images.githubusercontent.com/8102654/79962296-289cba00-8488-11ea-97ff-55813bd3eaf7.png)

Here, the 'ROOT' span belonging only to 'zio-backend' was merely created when instantiating the module, and is probably of no interest to the user. The only correct one is the second reported trace (having 2 spans) it seems?

When implementing https://github.com/zio/zio-telemetry/pull/119, the same behaviour was encountered at first. It was solved by instantiating the module with a noop, default span.

There exists also a noop span for OpenTracing, and the same approach as OpenTelemetry will probably resolve the issue. Note that it will also solve the burden of choice the user has right now when choosing a rootspan when instantiating the module. (Even though a default name is provided, naming of the root span is probably not something that should be of relevance when instantiating the layer)

**Comment by arjun-1** [comment] 2020-04-24 22:40
After investigating a possible solution using the noop span, it turns out that this indeed removes the redundant reported trace. It is unusable though, since any use of this noop span as root span (without setting it with a different 'real' span) as a parent span will cause an exception. The reason this does work in opentelemetry is because of differences between the libraries: https://github.com/opentracing/opentracing-java/issues/375

**Comment by runtologist** [comment] 2020-04-26 06:33
There aren't two spans per trace. The root span lives for the entire lifespan of the application, not per request. We chose this approach for the reason you just described. Does that make sense?

**Comment by arjun-1** [comment] 2020-04-26 07:35
Ah, thanks for the clarification. Yeah, one span per lifespan of the application would make sense as an approach. Although the aforementioned ROOT spans seem to show up per request, i.e. 1 request => 1 extra reported ROOT span:

![Screenshot from 2020-04-26 09-29-06](https://user-images.githubusercontent.com/8102654/80300898-b803df00-87a0-11ea-8ce8-85cc1c459dbd.png)

These reported ROOT spans have different SpanID's. Or could I be misinterpreting this data?

**Comment by runtologist** [comment] 2020-04-26 09:58
Then we should take a look at the example apps. Maybe they have a bug. I can take a look next week.

**Comment by Fristi** [comment] 2020-04-28 14:43
I can confirm this behavior

All root traces (104)

<img width="1657" alt="Screenshot 2020-04-28 at 16 41 00" src="https://user-images.githubusercontent.com/141265/80500937-20a0b680-896f-11ea-9af1-26f202b38d19.png">

All traces (228)
<img width="1650" alt="Screenshot 2020-04-28 at 16 40 27" src="https://user-images.githubusercontent.com/141265/80500950-239ba700-896f-11ea-8cb2-fe1390a048d9.png">

All traces contains cronjob traces and http endpoint traces. Both are started from a `ZIO.root(name)`

**Comment by Fristi** [comment] 2020-04-28 14:46
I can confirm this behavior

All root traces (104)

<img width="1657" alt="Screenshot 2020-04-28 at 16 41 00" src="https://user-images.githubusercontent.com/141265/80500937-20a0b680-896f-11ea-9af1-26f202b38d19.png">

All traces (228)
<img width="1650" alt="Screenshot 2020-04-28 at 16 40 27" src="https://user-images.githubusercontent.com/141265/80500950-239ba700-896f-11ea-8cb2-fe1390a048d9.png">

All traces contains cronjob traces and http endpoint traces. Both are started from a `ZIO.root(name)`

**Comment by runtologist** [comment] 2020-04-30 05:19
The way the examples are written, a fresh layer is provided per request. Every fresh layer creates a fresh root span. Passing around the ZLayer in the examples is the issue, that needs to be fixed I think.

**Comment by Fristi** [comment] 2020-04-30 11:50
The issue is this is that you already create a root span in the `OpenTracing.managed` function which is a good entry point function, but you allow in the `OpenTracing.Service` the user to create another root span using  the `root` function. That's why you see two root spans (or more depending how many times you call it)

I think you shouldn't offer the root function, upon calling managed you should name your root and provide some context maybe. Creating a root span is the entry point of your application. Which is is typically a HTTP request or a message received from an external system
Converting a `ZManaged` to a `ZLayer` is easy, and providing that layer at that point in your application should be no issue I guess

It's kinda similar to what nantchez does: https://github.com/tpolecat/natchez/blob/master/modules/core/src/main/scala/EntryPoint.scala

EntryPoint is where you allocate a `Resource[F, Span]` which is similar to `ZManaged`

**Comment by arjun-1** [comment] 2020-05-02 14:31
Hmm, if the issue appears in another case (which is not the example), that hints it might be caused by the tracing module itself.

I would argue that it's OK to have a `root` and `child` function exposed in the module. Although it feels a bit odd indeed to be able to specify the root span both when creating the dependency (`live(...)`), and while using the dependency `root(...)`.

Typically, defining the root span is not something I would expect when creating the dependency. In fact, many users might not even have any clue what to specify here when creating the tracing dependency. Indeed, such a choice users would typically face when dealing with their application at endpoint level.

Maybe another solution could be brought, inspired by the following function from [natchez tracing](https://github.com/tpolecat/natchez/blob/master/modules/core/src/main/scala/EntryPoint.scala#L31):
```scala
def continueOrElseRoot(name: String, kernel: Kernel): Resource[F, Span[F]]
```

Given that OpenTracing does not allow us to instatiate rootspans, the current behaviour for creating a child span (through `span`) can be remodeled as:
* if there is a current root, create a child of the current root, else
* create a root with the same parameters as were provided for child

This would imply `currentSpan` being optional, i.e. `Option[Span]`. Another benefit of this approach would be similar behaviour between OpenTracing and OpenTelemetry. I did a quick experiment what would happen if one decides to make a child span directly on the `DefaultSpan` that is used in OpenTelemetry (so without making a root). That created span is interpreted as a root span in the Jaeger UI.

**Comment by runtologist** [comment] 2020-05-04 04:43
We considered making the span optional, but that does not feel right for me. Without a span most  methods would need to fail of silently do a noop. That makes their behavior error prone I think.

There are use cases for creating the dependency with a root span as well as for crating a fresh root later. For example, we trace the application lifecycle but also create a fresh root per request if we do not receive a traceid one with the request. That means the root method is used as a fallback. For that kind of use we could introduce something like `extractOrRoot`. 

Creating a Layer per request also feels less than optimal, because the `Tracer` dependency needs to be passed around outside if the layer (as in the current example). If passing around the dependency separately is wished for, we could combine `layer` and `extract`.

If a user does not wish to have an initial root span, maybe an option would be to have the Tracer dependency in a separate layer and to use that as an input for `OpenTracing.layer`. The current `layer` would just be a shortcut then.

**Comment by grouzen** [comment] 2023-05-25 13:29
@arjun-1 Hello! Is this issue still relevant? Should we close it?

**Comment by grouzen** [comment] 2023-06-24 16:33
Closing it.

**Closed by grouzen** 2023-06-24 16:33 UTC
Labels: question
